import '../styles/globals.css'
import type { AppProps } from 'next/app'
import { MuiThemeProvider, CssBaseline } from "@material-ui/core";
import { ThemeProvider } from 'styled-components';
import theme from "../theme"
import { Header } from '../components/Header'
import Head from 'next/head'
import { Provider } from 'react-redux';
import { store, wrapper } from '../redux/store';
import { parseCookies } from 'nookies';
import { UserApi } from '../services/api';
import { setUser } from '../redux/slices/userSlice';


function App({ Component, pageProps }: AppProps) {
  return (
  
    <>
      <Head>
        <link rel="icon" href="/favicon.ico" />
        <title>Next News</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="" />
        <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" rel="stylesheet"></link>

      </Head>
      <MuiThemeProvider theme={theme}>
        <ThemeProvider theme={theme}>
          <CssBaseline />
          
            <Header />
            <Component {...pageProps} />
        </ThemeProvider>
      </MuiThemeProvider>
    </>
    
  )
}

App.getInitialProps = wrapper.getInitialAppProps(store => async ({ctx, Component}) => {
  try {

    const {token} = parseCookies(ctx)
    const user = await UserApi.getProfile(token)

    store.dispatch(setUser(user))

  } catch (error) {

    console.log(error)
    return { props: {} }
  }

  return { 
    pageProps: {
      ...(Component.getInitialProps ? await Component.getInitialProps({...ctx, store}) : {}),
     },
   }
})

export default wrapper.withRedux(App)
